#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  # java 6 require maven 3.2.5
  - wget http://mirrors.sonic.net/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
  - tar -zxf apache-maven-3.2.5-bin.tar.gz
  - sudo cp -R apache-maven-3.2.5 /usr/local
  - ls -lrt /usr/local/apache-maven-3.2.5/bin/
  - sudo ln -fs /usr/local/apache-maven-3.2.5/bin/mvn /usr/local/bin/mvn
  - export JAVA_HOME=$(/usr/libexec/java_home)
  - mvn --version
  - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc

install:
  # generate SSL certificates
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - env: DB=mariadb:10.1 PACKET=8M
      jdk: openjdk8
    - env: DB=mariadb:10.2 PACKET=8M
      jdk: openjdk8
    - env: DB=mariadb:10.3 PACKET=8M
      jdk: openjdk8
    - env: DB=mariadb:10.4 PACKET=8M
      jdk: openjdk8
    - env: DB=mariadb:10.5 PACKET=8M
      jdk: openjdk8
    - env: DB=mariadb:10.5 PACKET=8M
      jdk: openjdk11

script:
  - if [ "$DB" = "build" ] ; then .travis/build/build.sh; fi
  - if [ "$DB" = "build" ] ; then docker build -t build:latest --label build .travis/build/; fi
  - .travis/script.sh

after_success:
- bash <(curl -s https://codecov.io/bash)